repos:
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v1.3.5
    hooks:
    -   id: reorder-python-imports
-   repo: https://github.com/ambv/black
    rev: 18.9b0
    hooks:
    - id: black
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
    - id: trailing-whitespace
    - id: flake8
    - id: detect-private-key
    - id: end-of-file-fixer
    - id: check-yaml
-   repo: https://github.com/pre-commit/mirrors-pylint
    rev: v2.3.0.dev1
    hooks:
    - id: pylint
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.660
    hooks:
    - id: mypy
-   repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
    rev: v1.0.3
    hooks:
    -   id: python-bandit-vulnerability-check
-   repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    sha: v1.1.0
    hooks:
    -   id: python-safety-dependencies-check
